# Project
version=4.0.3.5
group=dev.corgitaco
archives_base_name=Corgilib

# Upload IDs
curseforge_id=693313
modrinth_id=ziOp6EO8

# Common
minecraft_version=1.20.1

# Forge
forge_version=47.4.9
neoforge_version=47.1.106
use_neoforge=false

# Fabric
fabric_api_version=0.92.6
fabric_loader_version=0.17.2

# Mod options
mod_name=CorgiLib
mod_author=Corgi Taco
mod_id=corgilib

# Mappings
parchment=2023.09.03

# Deps
nightconfig_version=3.8.3
jankson_version=1.2.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
